!q::Send "{Esc}"
!Space::Send "{Enter}"
!j::Send "{Left}"
!i::Send "{Up}"
!l::Send "{Right}"
!k::Send "{Down}"
!u::Send "{Home}"
!o::Send "{End}"
!h::Send "{Backspace}"
!+j::Send "{Shift down}{Left}{Shift up}"
!+i::Send "{Shift down}{Up}{Shift up}"
!+l::Send "{Shift down}{Right}{Shift up}"
!+k::Send "{Shift down}{Down}{Shift up}"
!+u::Send "{Shift down}{Home}{Shift up}"
!+o::Send "{Shift down}{End}{Shift up}"
!+h::Send "{Shift down}{Backspace}{Shift up}"
^!+j::Send "{Ctrl down}{Shift down}{Left}{Shift up}{Ctrl up}"
^!+i::Send "{Ctrl down}{Shift down}{Up}{Shift up}{Ctrl up}"
^!+l::Send "{Ctrl down}{Shift down}{Right}{Shift up}{Ctrl up}"
^!+k::Send "{Ctrl down}{Shift down}{Down}{Shift up}{Ctrl up}"
^!+h::Send "{Ctrl down}{Shift down}{Backspace}{Shift up}{Ctrl up}"
^!h::Send "{Ctrl down}{Backspace}{Ctrl up}"
